export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const FROM_CHANGE_INPUT = 'FROM_CHANGE_INPUT';
export const TO_CHANGE_INPUT = 'TO_CHANGE_INPUT';
export const FROM_CURRENCY_CHANGE = 'FROM_CURRENCY_CHANGE';
export const TO_CURRENCY_CHANGE = 'TO_CURRENCY_CHANGE';
export const HANDLE_ERROR = 'HANDLE_ERROR';
